### ISSUE TITLE
Need for plugin

### ISSUE THREAD

**Issue by LukeTowers** [albrightlabs/nofrontend-plugin#1]
Out of curiosity, what does this plugin do that simply removing the CMS module from `cms.loadModules` (or whatever it's called in October 2.0), setting the `backendUrl` to `/` in the config files, and removing the `october/cms` requirement from your composer.json file wouldn't?

I've done that for several sites to have a "backend only" version of October / Winter and it works just fine.

**Comment by joebuonocore** [comment]
@LukeTowers nothing, apparently! It adds a line of CSS to hide the scope icon in the navigation but _initially_ the reason was because on Windows, setting `backend_uri` to `/` would cause a redirect issue. I've tested some more after you opened the issue, and it seems setting the value blank works as intended. Thanks for the nudge to dig deeper! We'll likely deprecate the plugin.

**Comment by LukeTowers** [comment]
No problem! There's so much hidden functionality in October and Winter it can be difficult to know if something already exists or not :) 

When I first started using October I spent a solid week reimplemting a version of the relation controller because I had no idea it existed 😂

**Comment by joebuonocore** [comment]
@LukeTowers You're right about that and clearly, I've been in a similar situation!
